Feature/game date
eracknaphobia/plugin.video.nhlgcl pull request #24
Opened 2021-02-01 01:03 UTC by mrawji

When looking at my favorite team's past games, I found it hard to make sure i was looking at the correct games.

This feature adds dates to that page, and leaves the other pages alone.
It also adds a "Starting at" prefix for some of the games. See the attached screenshots

![My Team Recent Game - Orignal](https://user-images.githubusercontent.com/563547/106403995-fdb39f00-63e5-11eb-916c-ee3381db82a2.png)

![My Team Recent Game - With the Change](https://user-images.githubusercontent.com/563547/106404002-04daad00-63e6-11eb-9008-39000a5f6d5e.png)
![Showing the Starting At](https://user-images.githubusercontent.com/563547/106404005-07d59d80-63e6-11eb-844c-c93e9a929422.png)

2021-02-03 00:40 UTC, eracknaphobia requested changes
I really like the date in the recent games list, nice work! I just would like to slim down the start time. Thanks for the PR!

2021-02-03 00:40 UTC, eracknaphobia commented on resources/lib/nhl_tv.py
> +        game_line_header = '%s %s' % (LOCAL_STRING(30023), game_time)
I think displaying the start time should be enough here.

2021-02-03 00:40 UTC, eracknaphobia commented on resources/language/resource.language.en_gb/strings.po
> +msgid "Starting at"
I think having the start time in the label makes it apparent the game has not started.

2021-02-03 01:10 UTC, mrawji commented
Agreed. Will make another tonight or tomorrow

On Tue, Feb 2, 2021, 4:40 PM eracknaphobia <notifications@github.com> wrote:

> *@eracknaphobia* requested changes on this pull request.
>
> I really like the date in the recent games list, nice work! I just would
> like to slim down the start time. Thanks for the PR!
> ------------------------------
>
> In resources/lib/nhl_tv.py
> <https://github.com/eracknaphobia/plugin.video.nhlgcl/pull/24#discussion_r569027475>
> :
>
> >          if TIME_FORMAT == '0':
>              game_time = game_time.strftime('%I:%M %p').lstrip('0')
>          else:
>              game_time = game_time.strftime('%H:%M')
> +        game_line_header = '%s %s' % (LOCAL_STRING(30023), game_time)
>
> I think displaying the start time should be enough here.
> ------------------------------
>
> In resources/language/resource.language.en_gb/strings.po
> <https://github.com/eracknaphobia/plugin.video.nhlgcl/pull/24#discussion_r569028576>
> :
>
> > @@ -36,6 +36,9 @@ msgctxt "#30022"
>  msgid "Recap"
>  msgstr ""
>
> +msgctxt "#30023"
> +msgid "Starting at"
>
> I think having the start time in the label makes it apparent the game has
> not started.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/eracknaphobia/plugin.video.nhlgcl/pull/24#pullrequestreview-581891577>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEJSW345A46WWN2XWZ4TOTS5CLQVANCNFSM4W343O6Q>
> .
>

2021-02-03 03:26 UTC, mrawji commented
Should be ok now (this the first time I've done a PR with a rebase. LMK if I messed it up).
Marc

2021-02-04 01:19 UTC, merged

2021-02-04 01:27 UTC, eracknaphobia commented
Looks good, thanks!